name: Create Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7

    - name: configure_macos
      if: matrix.os == 'macos-latest'
      run: mkdir build && cd build && cmake -G Xcode ..

    - name: configure_windows
      if: matrix.os == 'windows-latest'
      run: mkdir build && cd build && cmake ..

    - name: build
      run: cmake --build build --config 'Release'

    - name: package_macos
      if: matrix.os == 'macos-latest'
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        PACKAGE_NAME=`echo $GITHUB_REPOSITORY | sed 's/.*\///g'`
        mkdir -p $PACKAGE_NAME
        if [ -e package-info.json ]; then cp package-info.json $PACKAGE_NAME; fi
        for f in *.md; do [ -e "$f" ] && cp "$f" $PACKAGE_NAME ; done
        if [ -e icon.png ]; then cp icon.png $PACKAGE_NAME; fi
        if [ -d docs ]; then cp -a docs $PACKAGE_NAME; fi
        if [ -d examples ]; then cp -a examples $PACKAGE_NAME; fi
        if [ -d externals ]; then cp -a externals $PACKAGE_NAME; fi
        if [ -d extras ]; then cp -a extras $PACKAGE_NAME; fi
        if [ -d help ]; then cp -a help $PACKAGE_NAME; fi
        if [ -d init ]; then cp -a init $PACKAGE_NAME; fi
        if [ -d media ]; then cp -a media $PACKAGE_NAME; fi
        if [ -d patchers ]; then cp -a patchers $PACKAGE_NAME; fi

    - name: package_windows
      if: matrix.os == 'windows-latest'
      shell: cmd
      env:
        GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
      run: |
        set PACKAGE_NAME=%GITHUB_REPOSITORY_NAME%
        mkdir %PACKAGE_NAME%
        if exist extensions cp -a extensions %PACKAGE_NAME%
        if exist externals cp -a externals %PACKAGE_NAME%
        if exist support cp -a support %PACKAGE_NAME%

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ steps.short-sha.outputs.sha }}-release-${{ matrix.os }}
        path: ${{ github.event.repository.name }}

  bundle:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7

    - uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ steps.short-sha.outputs.sha }}-release-windows-latest
        path: ${{ github.event.repository.name }}

    - uses: actions/download-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ steps.short-sha.outputs.sha }}-release-macos-latest
        path: ${{ github.event.repository.name }}

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ${{ github.event.repository.name }}

    - name: zip
      run: zip -r ${{ github.event.repository.name }}-package-for-max-${{ steps.short-sha.outputs.sha }}.zip ${{ github.event.repository.name }}

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ steps.short-sha.outputs.sha }}-package
        path: ${{ github.event.repository.name }}-package-for-max-${{ steps.short-sha.outputs.sha }}.zip
